### ISSUE TITLE
[Bug] 前端编译有错误

### ISSUE THREAD

**Issue by WUZHUHE38** [isxcode/spark-yun#1086]
### Branch name (分支名)

main

### Bug description (缺陷描述)

![QQ截图20240813115035](https://github.com/user-attachments/assets/ed10763a-73ca-4576-a26c-4c526213fd63)

### Reproduction steps (复现步骤)

nrm use taobao  pnpm i

**Comment by WUZHUHE38** [comment]
不好意思 用yarn解决了

**Comment by ispong** [comment]
推荐根据官网readme，去编译项目
![image](https://github.com/user-attachments/assets/fe2d63dc-0d8e-4953-9e65-e98efa1f1fd5)
