### ISSUE TITLE
大佬请教下官网的这个云在线演示是开源的吗。

### ISSUE THREAD

**Issue by zhangle1** [isxcode/spark-yun#1145]
就是这个仓库吗

**Comment by ispong** [comment]
许可证是永久免费的

**Comment by ispong** [comment]
参考快速部署文档： https://zhiqingyun.isxcode.com/docs/zh/1/0-docker

**Comment by zhangle1** [comment]
嗯 我学习下  准备引入看看

**Comment by ispong** [comment]
> 嗯 我学习下 准备引入看看

可以加我微信，wx_ispong，遇到问题帮你解决
