### ISSUE TITLE
[Bug] sqlserver采集异常

### ISSUE THREAD

**Issue by ispong** [isxcode/spark-yun#1248]
### Branch name (分支名)

main

### Bug description (缺陷描述)

![image](https://github.com/user-attachments/assets/a969bad6-bc7a-425f-bba6-e57078637d26)

**Comment by Gilnelisex** [comment]
sqlserver表名不支持部分特殊字符，即使用[]括住进行查询也会报这个错，应该是sqlserver本身的问题

**Comment by Gilnelisex** [comment]
![img_v3_02fi_9b1522e2-5bf1-4dac-afba-79579e425abg](https://github.com/user-attachments/assets/0eef65ca-d12d-4f70-ba97-a53f6e697c72)
