### ISSUE TITLE
[Bug] mysql 驱动错误，无法连接 mysql 服务器

### ISSUE THREAD

**Issue by geekyouth** [isxcode/spark-yun#1249]
### Branch name (分支名)

main

### Bug description (缺陷描述)

docker 日志：
```
2024-10-11 12:47:42.546 ERROR 7 --- [nio-8080-exec-6] c.i.s.m.datasource.source.Datasource     : com.mysql.cj.jdbc.Driver
2024-10-11T04:47:42.547415540Z 
2024-10-11T04:47:42.547422040Z java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver
2024-10-11T04:47:42.547424740Z 	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_342]
2024-10-11T04:47:42.547427340Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_342]
2024-10-11T04:47:42.547429640Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_342]
2024-10-11T04:47:42.547432140Z 	at com.isxcode.star.modules.datasource.source.Datasource.getConnection(Datasource.java:103) ~[spark-yun-modules-GH-1211-plain.jar!/:na]
2024-10-11T04:47:42.547434540Z 	at com.isxcode.star.modules.datasource.service.biz.DatasourceBizService.testConnect(DatasourceBizService.java:189) 
```

![image](https://github.com/user-attachments/assets/1d833a97-20a6-43c3-b5a2-dd4dc0f51230)
![image](https://github.com/user-attachments/assets/34ff9595-cdb5-4595-a402-0a50db8550f7)

**Comment by ispong** [comment]
> ### Branch name (分支名)
> main
> 
> ### Bug description (缺陷描述)
> docker 日志：
> 
> ```
> 2024-10-11 12:47:42.546 ERROR 7 --- [nio-8080-exec-6] c.i.s.m.datasource.source.Datasource     : com.mysql.cj.jdbc.Driver
> 2024-10-11T04:47:42.547415540Z 
> 2024-10-11T04:47:42.547422040Z java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver
> 2024-10-11T04:47:42.547424740Z 	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_342]
> 2024-10-11T04:47:42.547427340Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_342]
> 2024-10-11T04:47:42.547429640Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_342]
> 2024-10-11T04:47:42.547432140Z 	at com.isxcode.star.modules.datasource.source.Datasource.getConnection(Datasource.java:103) ~[spark-yun-modules-GH-1211-plain.jar!/:na]
> 2024-10-11T04:47:42.547434540Z 	at com.isxcode.star.modules.datasource.service.biz.DatasourceBizService.testConnect(DatasourceBizService.java:189) 
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/12899262/375629603-1d833a97-20a6-43c3-b5a2-dd4dc0f51230.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzQ5ODEsIm5iZiI6MTcyODYzNDY4MSwicGF0aCI6Ii8xMjg5OTI2Mi8zNzU2Mjk2MDMtMWQ4MzNhOTctMjBhNi00M2MzLWI1YTItZGQ0ZGMwZjUxMjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA4MTgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NzU0Nzg0YzU0OTEyMWNiMDcwYWYzZDkyYTZmZGYxMTVjMDc5Zjg3MThjZTI2NTFkY2Q5Y2IyNjI0ZDY1MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1GwknQMS84RYOCaocyD3LXdeD-vHwWPEKPKH9jjgCa0) ![image](https://private-user-images.githubusercontent.com/12899262/375629612-34ff9595-cdb5-4595-a402-0a50db8550f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzQ5ODEsIm5iZiI6MTcyODYzNDY4MSwicGF0aCI6Ii8xMjg5OTI2Mi8zNzU2Mjk2MTItMzRmZjk1OTUtY2RiNS00NTk1LWE0MDItMGE1MGRiODU1MGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA4MTgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZWM5M2M0MzM1NGQ2MGNmZTAzNTI0MWI2MjZjYWQwNTI2MjBkNmQzNWRlMTNlOTVkYjRjOGNhMmU4YjBhYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.klAtyLO0LHS0Pf_Lx7sGigXCxqFzWGvB-lpBvG86vXQ)
> 
> ### Reproduction steps (复现步骤)
> _No response_
> 
> ### cUrls and response (请求和响应)
> _No response_

参考官网部署手册： https://zhiqingyun.isxcode.com/docs/zh/1/0-docker

![image](https://github.com/user-attachments/assets/2059b17e-e75c-4ad2-9cb9-586013ad2a60)

应该是文件路径映射异常了

**Comment by ispong** [comment]
检查一下，resources/jdbc 目录下是否有驱动文件

**Comment by ispong** [comment]
检查一下，docker文件映射位置是否正确

**Comment by ispong** [comment]
参考官网部署手册： https://zhiqingyun.isxcode.com/docs/zh/1/0-docker

![image](https://github.com/user-attachments/assets/2059b17e-e75c-4ad2-9cb9-586013ad2a60)

应该是文件路径映射异常了

**Comment by geekyouth** [comment]
明白了，这两处标记的地方必须同时操作，希望文档注明一下吧，docker 最佳实践应该不建议拷贝容器中的大文件到本地，可以单独设置一个卷从本地映射到容器中，用来自定义驱动 
![image](https://github.com/user-attachments/assets/f0dc8a48-89fe-4c59-b715-70f4f3902ce4)

**Comment by geekyouth** [comment]
容器中 /etc/zhiqingyun/conf 配置文件拷贝出来挂载到容器后，为什么以下链接无法访问呢，报错 403
```
  # druid: http://localhost:8080/druid/index.html
  # h2: http://localhost:8080/h2-console
  # swagger: http://localhost:8080/swagger-ui/index.html
```
 
![image](https://github.com/user-attachments/assets/eae65f5b-bbec-4615-8baa-6b0ae5db4f09)

![image](https://github.com/user-attachments/assets/82469ad0-f5f7-4e82-9f96-1b93b0776690)

**Comment by ispong** [comment]
需要使用浏览器的无痕模式访问

**Comment by ispong** [comment]
是的，docker的路径配置问题，已经提了issue。

**Comment by geekyouth** [comment]
> 需要使用浏览器的无痕模式访问 这些地址一般不让用户访问，只让开发者进行访问的

我开了无痕模式，也还是无法访问啊，本质就是清掉 cookie 啊，但是这种管理页面理论上应该是需要授权访问而不是公开访问
