### ISSUE TITLE
[Improve] 建议将证书文件默认持久化到宿主机磁盘

### ISSUE THREAD

**Issue by geekyouth** [isxcode/spark-yun#1273]
### Branch name (分支名)

main

### Improve description (优化建议)

docker-compose down 之后 up 一下，证书没了，可以在 docker image 中默认做个持久化到宿主机

![image](https://github.com/user-attachments/assets/3f964b4d-cc26-4b84-95f6-737984a0284c)

**Comment by ispong** [comment]
添加路径映射可以持久化许可证
举例：
docker run --restart=always \
    --name zhiqingyun\
    -v /Users/ispong/Downloads/zhiqingyun:/var/lib/zhiqingyun \
    -p 8080:8080 \
    -d isxcode/zhiqingyun:GH-1211
    
 /var/lib/zhiqingyun 路径下包含 
  - /h2 : 数据库 
  - /jdbc ： 自己上传的驱动
  - /file ： 资源中心文件
  - /license ：许可证
  - /logs ： 归档日志
