### ISSUE TITLE
[Bug] git bash运行启动命令，日志中文乱码

### ISSUE THREAD

**Issue by ispong** [isxcode/spark-yun#1277]
### Which operating systems have you used (部署的操作系统)

- [ ] macOS
- [X] Windows
- [ ] Linux

### Download from (安装来源)

- [X] 本地源码编译
- [ ] 官网二进制
- [ ] 阿里镜像仓库
- [ ] Docker Hub

### Version number (当前版本号，获取方式：http://localhost:8080/tools/open/version)

latest

### Bug description (缺陷描述)

![image](https://github.com/user-attachments/assets/a80f1f42-3ec4-4f6c-9b85-f46b8ba49e90)

**Comment by Gilnelisex** [comment]
gradle编码问题，在命令后添加git bash指定的编码参数即可， 例如：-Dfile.encoding=UTF-8
![image](https://github.com/user-attachments/assets/3e028dc5-a6e3-4dc0-988a-b904218b202c)
