### ISSUE TITLE
使用自定义的oracle驱动可以测试连接成功，但是在数据同步中拉取不到表

### ISSUE THREAD

**Issue by Sai1boats** [isxcode/spark-yun#562]
### Branch name (分支名)

main

### Bug description (缺陷描述)

测试连接通过，使用的自己上传的驱动
<img width="1708" alt="image" src="https://github.com/isxcode/spark-yun/assets/44129590/b78e9c1e-08d9-4a9e-8706-7c3d4dc59ee0">
但是在拉取表数据时会提示找不到class
<img width="1708" alt="image" src="https://github.com/isxcode/spark-yun/assets/44129590/6d49d130-4a4f-4dce-ab78-2b9441db8ea8">

{
    "code": "200",
    "msg": "java.lang.ClassNotFoundException: oracle.jdbc.driver.OracleDriver"
}

附件为使用的驱动
[ojdbc8-18.15.0.0.jar.zip](https://github.com/isxcode/spark-yun/files/14545291/ojdbc8-18.15.0.0.jar.zip)

**Comment by Gilnelisex** [comment]
驱动文件未解压，解压后上传就可以用了

**Comment by Gilnelisex** [comment]
驱动文件为.zip格式，上传驱动时应该未解压，只有直接上传jar.zip后查询表才会报这个错，解压后上传就可以正常使用了
