### ISSUE TITLE
前端实例图,收起异常

### ISSUE THREAD

**Issue by ispong** [isxcode/spark-yun#667]
### Branch name (分支名)

main

**Comment by ispong** [comment]
实例列表刷新按钮无效

**Comment by ispong** [comment]
集群监控的设置按钮改为刷新按钮

**Comment by ispong** [comment]
实例图,不要0.5的比例,整数即可
![image](https://github.com/isxcode/spark-yun/assets/34756621/424a8c63-a4ad-4571-90fa-8e8916e5c76d)

**Comment by BeyondJSC** [comment]
> 实例图,不要0.5的比例,整数即可 ![image](https://private-user-images.githubusercontent.com/34756621/319723855-424a8c63-a4ad-4571-90fa-8e8916e5c76d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTM1MjcsIm5iZiI6MTcxMjY1MzIyNywicGF0aCI6Ii8zNDc1NjYyMS8zMTk3MjM4NTUtNDI0YThjNjMtYTRhZC00NTcxLTkwZmEtOGU4OTE2ZTVjNzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA5MDAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YzRmNTc5NWExYWE4OWQxYzBkNDRhODRkZDZiMmZjY2YzOGQ2YzRkNjY4NDYzOWEzMGU3ZTE4NWQzZWEwYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HDE-4W5GKzFv94CDyfMrHYYY9ctNsYtB5e0d34qHfj4)

这个比例是由返回的数据决定的，echart 插件会根据返回的数组动态调整比例

**Comment by BeyondJSC** [comment]
#685
