### ISSUE TITLE
首页监控,系统信息异常

### ISSUE THREAD

**Issue by ispong** [isxcode/spark-yun#676]
### Branch name (分支名)

main

### Bug description (缺陷描述)

![image](https://github.com/isxcode/spark-yun/assets/34756621/15fd21f2-ff2d-4d94-8a58-007f58b17452)

**Comment by ispong** [comment]
![image](https://github.com/isxcode/spark-yun/assets/34756621/8ad2a9eb-2473-4f28-964d-4ed6b1c51927)

给个暂无数据吧

**Comment by BeyondJSC** [comment]
ok
